version: "3"
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
    volumes:
      - etcd_data:/etcd
volumes:
  etcd_data:
    driver: local
